export const DOCS_BASE_URL = "https://docs.reservoir.tools/docs/";
export const API_DOCS_BASE_URL = "https://docs.reservoir.tools/reference/";

export const headers = {
  accept: "*/*",
  "accept-language": "en-US,en;q=0.9",
  "cache-control": "no-cache",
  pragma: "no-cache",
  "sec-ch-ua": '"Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"',
  "sec-ch-ua-mobile": "?0",
  "sec-ch-ua-platform": '"macOS"',
  "sec-fetch-dest": "empty",
  "sec-fetch-mode": "cors",
  "sec-fetch-site": "same-origin",
  "x-requested-with": "XMLHttpRequest",
  Referer: "https://docs.reservoir.tools/docs",
  "Referrer-Policy": "strict-origin-when-cross-origin",
};

// TODO - automatically pull all docs
export const slugs = [
  "what-is-reservoir",
  "supported-marketplaces",
  "supported-chains",
  "faq",
  "nft-liquidity-router",
  "data-lake",
  "indexer",
  "marketplace-toolkit",
  "typescript-api-typings",
  "buytoken",
  "listtoken",
  "placebid",
  "acceptoffer",
  "cancelorder",
  "sweeping",
  "buying",
  "listing",
  "bidding",
  "accept-bid",
  "add-a-cart",
  "cancel-a-listing",
  "cancel-a-listing-1",
  "reservoir-kit-theming-and-customization",
  "tokenmedia",
  "rk-ui-troubleshooting",
  "reservoirkit-ui",
  "reservoir-sdk",
  "usetokens",
  "usecollections",
  "usecollectionactivity",
  "useusersactivity",
  "usetokenactivity",
  "uselistings",
  "useownerlistings",
  "usereservoirclient",
  "detect-tokens-flagged-by-opensea",
  "useattributes",
  "usebids",
  "useusertopbids",
  "useusercollections",
  "useusertokens",
  "usecart",
  "usedynamictokens",
  "marketplace",
  "custom-marketplaces",
  "aggregated-liquidity",
  "data-and-analytics",
  "market-making",
  "understanding-sales",
  "filling-existing-liquidity",
  "full-support",
  "walletportfolio-app",
  "calldata-attribution",
  "add-instant-sell",
  "buy-sweep",
  "bulk-order-creation",
  "floor-prices",
  "adding-support-for-custom-erc-20-token",
  "flagged-tokens",
  "royalties",
  "custom-fees",
  "realtime-websocket-events",
  "hosting-a-reservoir-discord-nft-bot",
  "accessing-native-liquidity",
  "hosted-vs-self-hosted",
  "filling-orders-explainer",
  "marketplace-fees-royalties",
  "blur-limitations",
  "built-on-reservoir",
  "security-and-smart-contract-audits",
  "glossary",
  "logos",
];
